import {
  ClerkProvider,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Toaster } from '@/components/ui/sonner'
import LenisProvider from '@/lib/LenisProvider';
import RouteLoader from '@/components/RouteLoader';
import ConditionalHeader from '@/components/ConditionalHeader';
import ConditionalWrapper from '@/components/ConditionalWrapper';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata = {
  title: 'SkillLens',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <LenisProvider>
      <RouteLoader />
      <ClerkProvider>
        <html lang="en">
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            
            {/* Conditional Header - Hidden on HOD pages */}
            <ConditionalHeader />

            {/* Page Content - Conditional padding */}
            <ConditionalWrapper>
              {children}
            </ConditionalWrapper>

            {/* Footer */}
            <footer className="bg-black py-12">
              <div className="container mx-auto px-4 text-center text-gray-200">
                <p>Made with 💗 by Teja</p>
              </div>
            </footer>
            
            {/* Toast Notifications */}
            <Toaster />
          </body>
        </html>
      </ClerkProvider>
    </LenisProvider>
  )
}
